import { pool } from "../config/db.js"

export const register = async (name,
    email,
    national_id,
    phone_number,
    address,
    birth_date,
    gender,
    password,
    nationality,
    has_passport,
    passportId,
    role) => {
        const result = await pool.query(`insert into users(name,
        email,
        national_id,
        phone_number,
        address,
        birth_date,
        gender,
        password,
        nationality,
        has_passport,
        passportId,
        role) values($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning *`, [name,
            email,
            national_id,
            phone_number,
            address,
            birth_date,
            gender,
            password,
            nationality,
            has_passport,
            passportId,
            role])
        return result.rows[0]
    }
